name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Archive project files
      run: tar -czf my-app.tar.gz .

    - name: Upload archive
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: my-app.tar.gz

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          mkdir -p ~/deploy
          cd ~/deploy
          rm -rf *
          tar -xzf /tmp/my-app.tar.gz
          docker-compose down
          docker-compose up -d

    - name: Download archive on EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "my-app.tar.gz"
        target: "/tmp/"
